### ISSUE TITLE
error verification 

### ISSUE THREAD

**Issue by joaokristani** [shadowplay1/discord-economy-super#37]
my code: 	
```
async execute({ inter }) {
		const daily = await eco.rewards.getDaily(inter.user.id, inter.guild.id);

		if (!daily.claimed) {
			const embedNoDaily = new EmbedBuilder()
				.setDescription('result')
				.setColor('#d72b07');
			await inter.reply({ embeds: [embedNoDaily] });
		}
		const embedDaily = new EmbedBuilder()
			.setDescription(`${daily.reward}`)
			.setColor('#d72b07');
		await inter.reply({ embeds: [embedDaily] });
    }}
```
   
I'm using **discord-economy-super 1.7.6** where it has the `Status -> claimed` update
the error is the following: it does not check or save the daily or any other Cooldown, I am using mongoDB with the example configuration, in version **1.7.4** with `daily.status` it works normally, it just happens in this specific version

**Comment by joaokristani** [comment]
simply after I stopped the project and came back now the package started working normally, I didn't change anything

**Comment by shadowplay1** [comment]
lol
