### ISSUE TITLE
Module Issue

### ISSUE THREAD

**Issue by MCRaspRBX** [shadowplay1/discord-economy-super#5]
i installed it set it up and when try boot my bot it gave this: 
node:internal/modules/cjs/loader:930
  throw err;
  ^

Error: Cannot find module '../structures/Errors'
Require stack:
- /home/raspberryrbx/Desktop/RBXBot-Private/node_modules/discord-economy-super/src/managers/BankManager.js
- /home/raspberryrbx/Desktop/RBXBot-Private/node_modules/discord-economy-super/src/index.js
- /home/raspberryrbx/Desktop/RBXBot-Private/node_modules/discord-economy-super/index.js
- /home/raspberryrbx/Desktop/RBXBot-Private/index.js

**Comment by shadowplay1** [comment]
Will be fixed as soon as possible, sorry for that :)

**Comment by shadowplay1** [comment]
fixed in 1.3.4 :)

**Comment by MCRaspRBX** [comment]
Ok I won't be using the npm tho now I started using quick.db for economy
